const data = {
  AF: [93, 'Afghanistan (‫افغانستان‬‎)'],
  AL: [355, 'Albania (Shqipëri)'],
  DZ: [213, 'Algeria (‫الجزائر‬‎)'],
  AS: [1684, 'American Samoa'],
  AD: [376, 'Andorra'],
  AO: [244, 'Angola'],
  AI: [1264, 'Anguilla'],
  AG: [1268, 'Antigua and Barbuda'],
  AR: [54, 'Argentina'],
  AM: [374, 'Armenia (Հայաստան)'],
  AW: [297, 'Aruba'],
  AU: [61, 'Australia'],
  AT: [43, 'Austria (Österreich)'],
  AZ: [994, 'Azerbaijan (Azərbaycan)'],
  BS: [1242, 'Bahamas'],
  BH: [973, 'Bahrain (‫البحرين‬‎)'],
  BD: [880, 'Bangladesh (বাংলাদেশ)'],
  BB: [1246, 'Barbados'],
  BY: [375, 'Belarus (Беларусь)'],
  BE: [32, 'Belgium (België)'],
  BZ: [501, 'Belize'],
  BJ: [229, 'Benin (Bénin)'],
  BM: [1441, 'Bermuda'],
  BT: [975, 'Bhutan (འབྲུག)'],
  BO: [591, 'Bolivia'],
  BA: [387, 'Bosnia and Herzegovina (Босна и Херцеговина)'],
  BW: [267, 'Botswana'],
  BR: [55, 'Brazil (Brasil)'],
  IO: [246, 'British Indian Ocean Territory'],
  VG: [1284, 'British Virgin Islands'],
  BN: [673, 'Brunei'],
  BG: [359, 'Bulgaria (България)'],
  BF: [226, 'Burkina Faso'],
  BI: [257, 'Burundi (Uburundi)'],
  KH: [855, 'Cambodia (កម្ពុជា)'],
  CM: [237, 'Cameroon (Cameroun)'],
  CA: [1, 'Canada'],
  CV: [238, 'Cape Verde (Kabu Verdi)'],
  BQ: [599, 'Caribbean Netherlands'],
  KY: [1345, 'Cayman Islands'],
  CF: [236, 'Central African Republic (République centrafricaine)'],
  TD: [235, 'Chad (Tchad)'],
  CL: [56, 'Chile'],
  CN: [86, 'China (中国)'],
  CX: [61, 'Christmas Island'],
  CC: [61, 'Cocos (Keeling) Islands'],
  CO: [57, 'Colombia'],
  KM: [269, 'Comoros (‫جزر القمر‬‎)'],
  CD: [243, 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)'],
  CG: [242, 'Congo (Republic) (Congo-Brazzaville)'],
  CK: [682, 'Cook Islands'],
  CR: [506, 'Costa Rica'],
  CI: [225, 'Côte d’Ivoire'],
  HR: [385, 'Croatia (Hrvatska)'],
  CU: [53, 'Cuba'],
  CW: [599, 'Curaçao'],
  CY: [357, 'Cyprus (Κύπρος)'],
  CZ: [420, 'Czech Republic (Česká republika)'],
  DK: [45, 'Denmark (Danmark)'],
  DJ: [253, 'Djibouti'],
  DM: [1767, 'Dominica'],
  DO: [1, 'Dominican Republic (República Dominicana)'],
  EC: [593, 'Ecuador'],
  EG: [20, 'Egypt (‫مصر‬‎)'],
  SV: [503, 'El Salvador'],
  GQ: [240, 'Equatorial Guinea (Guinea Ecuatorial)'],
  ER: [291, 'Eritrea'],
  EE: [372, 'Estonia (Eesti)'],
  ET: [251, 'Ethiopia'],
  FK: [500, 'Falkland Islands (Islas Malvinas)'],
  FO: [298, 'Faroe Islands (Føroyar)'],
  FJ: [679, 'Fiji'],
  FI: [358, 'Finland (Suomi)'],
  FR: [33, 'France'],
  GF: [594, 'French Guiana (Guyane française)'],
  PF: [689, 'French Polynesia (Polynésie française)'],
  GA: [241, 'Gabon'],
  GM: [220, 'Gambia'],
  GE: [995, 'Georgia (საქართველო)'],
  DE: [49, 'Germany (Deutschland)'],
  GH: [233, 'Ghana (Gaana)'],
  GI: [350, 'Gibraltar'],
  GR: [30, 'Greece (Ελλάδα)'],
  GL: [299, 'Greenland (Kalaallit Nunaat)'],
  GD: [1473, 'Grenada'],
  GP: [590, 'Guadeloupe'],
  GU: [1671, 'Guam'],
  GT: [502, 'Guatemala'],
  GG: [44, 'Guernsey'],
  GN: [224, 'Guinea (Guinée)'],
  GW: [245, 'Guinea-Bissau (Guiné Bissau)'],
  GY: [592, 'Guyana'],
  HT: [509, 'Haiti'],
  HN: [504, 'Honduras'],
  HK: [852, 'Hong Kong (香港)'],
  HU: [36, 'Hungary (Magyarország)'],
  IS: [354, 'Iceland (Ísland)'],
  IN: [91, 'India (भारत)'],
  ID: [62, 'Indonesia'],
  IR: [98, 'Iran (‫ایران‬‎)'],
  IQ: [964, 'Iraq (‫العراق‬‎)'],
  IE: [353, 'Ireland'],
  IM: [44, 'Isle of Man'],
  IL: [972, 'Israel (‫ישראל‬‎)'],
  IT: [39, 'Italy (Italia)'],
  JM: [1876, 'Jamaica'],
  JP: [81, 'Japan (日本)'],
  JE: [44, 'Jersey'],
  JO: [962, 'Jordan (‫الأردن‬‎)'],
  KZ: [7, 'Kazakhstan (Казахстан)'],
  KE: [254, 'Kenya'],
  KI: [686, 'Kiribati'],
  XK: [383, 'Kosovo'],
  KW: [965, 'Kuwait (‫الكويت‬‎)'],
  KG: [996, 'Kyrgyzstan (Кыргызстан)'],
  LA: [856, 'Laos (ລາວ)'],
  LV: [371, 'Latvia (Latvija)'],
  LB: [961, 'Lebanon (‫لبنان‬‎)'],
  LS: [266, 'Lesotho'],
  LR: [231, 'Liberia'],
  LY: [218, 'Libya (‫ليبيا‬‎)'],
  LI: [423, 'Liechtenstein'],
  LT: [370, 'Lithuania (Lietuva)'],
  LU: [352, 'Luxembourg'],
  MO: [853, 'Macau (澳門)'],
  MK: [389, 'Macedonia (FYROM) (Македонија)'],
  MG: [261, 'Madagascar (Madagasikara)'],
  MW: [265, 'Malawi'],
  MY: [60, 'Malaysia'],
  MV: [960, 'Maldives'],
  ML: [223, 'Mali'],
  MT: [356, 'Malta'],
  MH: [692, 'Marshall Islands'],
  MQ: [596, 'Martinique'],
  MR: [222, 'Mauritania (‫موريتانيا‬‎)'],
  MU: [230, 'Mauritius (Moris)'],
  YT: [262, 'Mayotte'],
  MX: [52, 'Mexico (México)'],
  FM: [691, 'Micronesia'],
  MD: [373, 'Moldova (Republica Moldova)'],
  MC: [377, 'Monaco'],
  MN: [976, 'Mongolia (Монгол)'],
  ME: [382, 'Montenegro (Crna Gora)'],
  MS: [1664, 'Montserrat'],
  MA: [212, 'Morocco (‫المغرب‬‎)'],
  MZ: [258, 'Mozambique (Moçambique)'],
  MM: [95, 'Myanmar (Burma) (မြန်မာ)'],
  NA: [264, 'Namibia (Namibië)'],
  NR: [674, 'Nauru'],
  NP: [977, 'Nepal (नेपाल)'],
  NL: [31, 'Netherlands (Nederland)'],
  NC: [687, 'New Caledonia (Nouvelle-Calédonie)'],
  NZ: [64, 'New Zealand'],
  NI: [505, 'Nicaragua'],
  NE: [227, 'Niger (Nijar)'],
  NG: [234, 'Nigeria'],
  NU: [683, 'Niue'],
  NF: [672, 'Norfolk Island'],
  KP: [850, 'North Korea (조선 민주주의 인민 공화국)'],
  MP: [1670, 'Northern Mariana Islands'],
  NO: [47, 'Norway (Norge)'],
  OM: [968, 'Oman (‫عُمان‬‎)'],
  PK: [92, 'Pakistan (‫پاکستان‬‎)'],
  PW: [680, 'Palau'],
  PS: [970, 'Palestine (‫فلسطين‬‎)'],
  PA: [507, 'Panama (Panamá)'],
  PG: [675, 'Papua New Guinea'],
  PY: [595, 'Paraguay'],
  PE: [51, 'Peru (Perú)'],
  PH: [63, 'Philippines'],
  PL: [48, 'Poland (Polska)'],
  PT: [351, 'Portugal'],
  PR: [1, 'Puerto Rico'],
  QA: [974, 'Qatar (‫قطر‬‎)'],
  RE: [262, 'Réunion (La Réunion)'],
  RO: [40, 'Romania (România)'],
  RU: [7, 'Russia (Россия)'],
  RW: [250, 'Rwanda'],
  BL: [590, 'Saint Barthélemy (Saint-Barthélemy)'],
  SH: [290, 'Saint Helena'],
  KN: [1869, 'Saint Kitts and Nevis'],
  LC: [1758, 'Saint Lucia'],
  MF: [590, 'Saint Martin (Saint-Martin (partie française))'],
  PM: [508, 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)'],
  VC: [1784, 'Saint Vincent and the Grenadines'],
  WS: [685, 'Samoa'],
  SM: [378, 'San Marino'],
  ST: [239, 'São Tomé and Príncipe (São Tomé e Príncipe)'],
  SA: [966, 'Saudi Arabia (‫المملكة العربية السعودية‬‎)'],
  SN: [221, 'Senegal (Sénégal)'],
  RS: [381, 'Serbia (Србија)'],
  SC: [248, 'Seychelles'],
  SL: [232, 'Sierra Leone'],
  SG: [65, 'Singapore'],
  SX: [1721, 'Sint Maarten'],
  SK: [421, 'Slovakia (Slovensko)'],
  SI: [386, 'Slovenia (Slovenija)'],
  SB: [677, 'Solomon Islands'],
  SO: [252, 'Somalia (Soomaaliya)'],
  ZA: [27, 'South Africa'],
  KR: [82, 'South Korea (대한민국)'],
  SS: [211, 'South Sudan (‫جنوب السودان‬‎)'],
  ES: [34, 'Spain (España)'],
  LK: [94, 'Sri Lanka (ශ්‍රී ලංකාව)'],
  SD: [249, 'Sudan (‫السودان‬‎)'],
  SR: [597, 'Suriname'],
  SJ: [47, 'Svalbard and Jan Mayen'],
  SZ: [268, 'Swaziland'],
  SE: [46, 'Sweden (Sverige)'],
  CH: [41, 'Switzerland (Schweiz)'],
  SY: [963, 'Syria (‫سوريا‬‎)'],
  TW: [886, 'Taiwan (台灣)'],
  TJ: [992, 'Tajikistan'],
  TZ: [255, 'Tanzania'],
  TH: [66, 'Thailand (ไทย)'],
  TL: [670, 'Timor-Leste'],
  TG: [228, 'Togo'],
  TK: [690, 'Tokelau'],
  TO: [676, 'Tonga'],
  TT: [1868, 'Trinidad and Tobago'],
  TN: [216, 'Tunisia (‫تونس‬‎)'],
  TR: [90, 'Turkey (Türkiye)'],
  TM: [993, 'Turkmenistan'],
  TC: [1649, 'Turks and Caicos Islands'],
  TV: [688, 'Tuvalu'],
  VI: [1340, 'U.S. Virgin Islands'],
  UG: [256, 'Uganda'],
  UA: [380, 'Ukraine (Україна)'],
  AE: [971, 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)'],
  GB: [44, 'United Kingdom'],
  US: [1, 'United States'],
  UY: [598, 'Uruguay'],
  UZ: [998, 'Uzbekistan (Oʻzbekiston)'],
  VU: [678, 'Vanuatu'],
  VA: [39, 'Vatican City (Città del Vaticano)'],
  VE: [58, 'Venezuela'],
  VN: [84, 'Vietnam (Việt Nam)'],
  WF: [681, 'Wallis and Futuna'],
  EH: [212, 'Western Sahara (‫الصحراء الغربية‬‎)'],
  YE: [967, 'Yemen (‫اليمن‬‎)'],
  ZM: [260, 'Zambia'],
  ZW: [263, 'Zimbabwe'],
  AX: [358, 'Åland Islands'],
};

export default data;
